export const DI_SYMBOLS = {
  EVENT_HTTP_INSTANCE: "EVENT_HTTP_INSTANCE",
  WORKFLOW_HTTP_INSTANCE: "WORKFLOW_HTTP_INSTANCE",
  LLM_CLIENT: "LLM_CLIENT",
  EVENT_DATE_PARSER: "EVENT_DATE_PARSER",
} as const;
